FROM debian:stable-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv iputils-ping && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY test/requirements.txt .
RUN pip install -r requirements.txt

COPY test/test.py .
COPY get_timestamp.sh .
RUN chmod +x get_timestamp.sh
COPY get_ping.sh .
RUN chmod +x get_ping.sh

CMD ["python", "-m", "pytest", "test.py", "-v"]